#!/usr/bin/env python3
"""
bayes_evidence.py — Nested Sampling integration pipeline for Green (2026)
Measures the formal Bayesian Evidence ln(Z) for the Two-Channel Model vs w0wa,
under the physical kappa in [0, 1] prior. Single-threaded (nlive=500), as originally run.

GUARD FIX (2026-07-07): the per-eval guard no longer promotes scipy quad's benign
roundoff/subdivision IntegrationWarnings to -inf (only genuine RuntimeWarnings), plus a
finite-chi2 check -- matching bayes_evidence_suite.py. The old guard rejected good points at
the two-channel model's best fit on scipy >= 1.11, biasing its ln(Z) LOW. Re-running this
script with the fix should raise Delta lnZ(C - w0wa) from the first-pass +0.356 toward ~+2.5
(the six-model suite value), confirming the bug. This script now auto-writes log-evidence-dr1-pair.txt.

Requires: pip install dynesty
Run via:  python3 bayes_evidence.py
"""

import numpy as np
import warnings
from dynesty import NestedSampler

# Force reproduction pipeline to load Pantheon+ data lazily into its namespace
import reproduce
import sys, os
DR2 = '--dr2' in sys.argv          # --dr2 switches reproduce's BAO block (shared argv)
REL = 'dr2' if DR2 else 'dr1'
_logf = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          f"log-evidence-{REL}-pair.txt"), 'w', encoding='utf-8')
sys.stdout = reproduce._Tee(sys.__stdout__, _logf)
print(f"# log-evidence-{REL}-pair.txt -- auto-generated by bayes_evidence.py"
      f"{' --dr2' if DR2 else ''}; two-channel vs w0wa, DESI {'DR2' if DR2 else 'DR1'} BAO")
reproduce.zs, reproduce.mb, reproduce.Cinv, reproduce.CinvO, reproduce.OCO = reproduce.get_sn()

# Test redshifts to check for physical viability out to recombination
TEST_ZS = np.array([0.0, 0.5, 1.0, 2.33, 10.0, 100.0, 1089.80])

# =====================================================================
# 1. TWO-CHANNEL ACCRETION MODEL WRAPPERS (ndim = 5)
# =====================================================================

def prior_transform_C(u):
    """Transforms uniform hypercube u ~ Unif(0, 1) to physical model priors."""
    p = np.empty_like(u)
    p[0] = 0.2 + 0.25 * u[0]   # Om:  [0.2, 0.45]
    p[1] = 60.0 + 16.0 * u[1]  # H0:  [60, 76]
    p[2] = 0.0 + 3.0 * u[2]    # mu0: [0, 3]
    p[3] = 0.5 + 11.5 * u[3]   # n:   [0.5, 12]
    p[4] = 0.0 + 1.0 * u[4]    # kap: [0, 1.0] <-- ENFORCING PHYSICAL EFFICIENCY BOUND
    return p

def log_likelihood_C(p):
    """Feeds nested sampler coordinates into reproduce's RK4 system with guards."""
    Om, H0, mu0, n, kap = p
    try:
        Hz = reproduce.Hz_C(p)
        
        # Guard Check: Catch unphysical/broken math before quad integration handles it
        for z_test in TEST_ZS:
            val = Hz(z_test)
            if np.isnan(val) or np.isinf(val) or val <= 0:
                return -np.inf

        # Reject only genuine numerical pathology (RuntimeWarning: overflow/invalid). Do NOT
        # promote scipy quad's benign roundoff/subdivision IntegrationWarnings to errors:
        # on scipy >= 1.11 they fire at this model's OWN best-fit point (chi2 still accurate
        # to ~7 digits), and rejecting those points biases the evidence LOW. The finite-chi2
        # check below is the real safeguard. (Guard-bug fix; see module docstring.)
        with warnings.catch_warnings():
            warnings.filterwarnings('error', category=RuntimeWarning)
            chi2_val = reproduce.chi2_blocks(Hz, Om, H0, with_sn=True)
    except Exception:
        return -np.inf
    if not np.isfinite(chi2_val):
        return -np.inf
    return -0.5 * chi2_val


# =====================================================================
# 2. w0-wa DM PARAMETERISATION WRAPPERS (ndim = 4)
# =====================================================================

def prior_transform_w0wa(u):
    """Transforms uniform hypercube u ~ Unif(0, 1) to empirical priors."""
    p = np.empty_like(u)
    p[0] = 0.2 + 0.25 * u[0]   # Om: [0.2, 0.45]
    p[1] = 60.0 + 16.0 * u[1]  # H0: [60, 76]
    p[2] = -2.5 + 2.5 * u[2]   # w0: [-2.5, 0.0]
    p[3] = -4.0 + 7.0 * u[3]   # wa: [-4.0, 3.0]
    return p

def log_likelihood_w0wa(p):
    """Feeds nested sampler coordinates into reproduce's w0wa fluid with guards."""
    Om, H0, w0, wa = p
    try:
        Hz = reproduce.Hz_w0wa(p)
        
        # Guard Check: Catch unphysical expansion states
        for z_test in TEST_ZS:
            val = Hz(z_test)
            if np.isnan(val) or np.isinf(val) or val <= 0:
                return -np.inf

        # Same guard fix as the two-channel wrapper (RuntimeWarning-only + finite-chi2 check).
        with warnings.catch_warnings():
            warnings.filterwarnings('error', category=RuntimeWarning)
            chi2_val = reproduce.chi2_blocks(Hz, Om, H0, with_sn=True)
    except Exception:
        return -np.inf
    if not np.isfinite(chi2_val):
        return -np.inf
    return -0.5 * chi2_val


# =====================================================================
# 3. MULTI-DIMENSIONAL INTEGRATION RUNNER
# =====================================================================

if __name__ == "__main__":
    print("\n" + "="*60)
    print(f"  NESTED SAMPLING EVIDENCE PIPELINE (Planck + DESI {'DR2' if DR2 else 'DR1'} + Pantheon+)")
    print("="*60 + "\n")
    
    print("Executing Run 1/2: Two-Channel Model Integration...")
    # ONE sampler per comparison, for a like-for-like pair. DR1 keeps the published default
    # ('auto' -> uniform); DR2 uses 'rslice' for BOTH models (uniform stalls on the two-channel
    # posterior there). rslice and uniform are unbiased estimators of the SAME evidence, so DR1's
    # published numbers are unchanged.
    _sample = 'rslice' if DR2 else 'auto'
    sampler_C = NestedSampler(log_likelihood_C, prior_transform_C, ndim=5, nlive=500, sample=_sample)
    sampler_C.run_nested()
    res_C = sampler_C.results
    logz_C, logz_err_C = res_C.logz[-1], res_C.logzerr[-1]
    print(f"--> Two-Channel Mechanism: ln(Z) = {logz_C:.3f} +/- {logz_err_C:.3f}\n")
    
    print("Executing Run 2/2: w0wa Empirical Parameterisation...")
    sampler_w = NestedSampler(log_likelihood_w0wa, prior_transform_w0wa, ndim=4, nlive=500, sample=_sample)
    sampler_w.run_nested()
    res_w = sampler_w.results
    logz_w, logz_err_w = res_w.logz[-1], res_w.logzerr[-1]
    print(f"--> empirical w0-wa model: ln(Z) = {logz_w:.3f} +/- {logz_err_w:.3f}\n")
    
    delta_logz = logz_C - logz_w
    odds_ratio = np.exp(abs(delta_logz))
    
    print("="*60)
    print("  FINAL BAYESIAN VERDICT")
    print("="*60)
    print(f"Delta ln(Z) [Two-Channel Model - w0wa] = {delta_logz:.3f}")
    
    if delta_logz > 0:
        print(f"The Two-Channel Accretion mechanism is preferred by odds of {odds_ratio:.2f} : 1")
        if delta_logz > 5.0:
            print("Strength of Evidence: DECISIVE")
        elif delta_logz > 2.5:
            print("Strength of Evidence: STRONG")
        elif delta_logz > 1.0:
            print("Strength of Evidence: POSITIVE")
        else:
            print("Strength of Evidence: INCONCLUSIVE")
    else:
        print(f"The empirical w0-wa model is preferred by odds of {odds_ratio:.2f} : 1")
    print("="*60 + "\n")
    sys.stdout = sys.__stdout__
    _logf.close()